name: GitHub Actions Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  schedule: 
    - cron: 15 6 * * SUN

jobs:
  build:
    name: Test GH Action
    runs-on: ubuntu-latest
    steps:
      - name: Display info
        run: |
          echo "Event --> ${{ github.event_name }}"
          echo "Ref --> ${{ github.ref_name }}"
          echo "Files:"
          ls -la
